apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          # image: us.gcr.io/golden-totality-364202/microservices-expiration
          image: joshuamr/expiration
          env:
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
            # Makes sure that we use the pod name for the client
            # id so it is traceable to the pod in logs
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name