name: tests-orders
on: 
  pull_request
  
jobs: 
  orders-test:
    name: orders-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
