name: tests-auth
on: 
  pull_request
  
jobs: 
  auth-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: auth/package-lock.json
      - name: Install dependencies
        working-directory: ./auth
        run: npm install 
      - name: Run tests
        working-directory: ./auth
        run: npm run test:ci
